{% set name = "skillbridge" %}
{% set version = "1.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/skillbridge-{{ version }}.tar.gz
  sha256: 41a3b2846d40949c82c1c42b29d9e361d9535bce2c978ec6bb91a32a715b492c

build:
  skip: true  # [py2k or win or osx]
  number: 0


requirements:
  host:
    - pip
    - python
  run:
    - dataclasses  # [py<37]
    - python

test:
  imports:
    - skillbridge
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/unihd-cag/skillbridge
  summary: A seamless Python remote bridge to Cadence's Skill in Virtuoso
  description: |
    The Python-Skill Bridge is a set of tools that allows you to control
    Virtuoso via its Skill console remotely from python
  license: LGPL-3.0-only
  license_file: LICENSE
  doc_url: https://unihd-cag.github.io/skillbridge/
  dev_url: https://github.com/unihd-cag/skillbridge

extra:
  recipe-maintainers:
    - curtisma
