{% set name = "skillbridge" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/skillbridge-{{ version }}.tar.gz
  sha256: c698839e3a048e6b40b3c6975c642a1d556bb0c07133dd0b74cb57fdd8dd43f5

build:
  skip: true  # [py2k or win or osx]
  number: 1


requirements:
  host:
    - pip
    - python
  run:
    - dataclasses  # [py<37]
    - python

test:
  imports:
    - skillbridge
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/unihd-cag/skillbridge
  summary: A seamless Python remote bridge to Cadence's Skill in Virtuoso
  description: |
    The Python-Skill Bridge is a set of tools that allows you to control
    Virtuoso via its Skill console remotely from python
  license: LGPL-3.0-only
  license_file: LICENSE
  doc_url: https://unihd-cag.github.io/skillbridge/
  dev_url: https://github.com/unihd-cag/skillbridge

extra:
  recipe-maintainers:
    - curtisma
